export const suggestions = [
  {
    min: 0,
    max: 100,
    category: [
      "Snacks",
      "Beverages",
      "Books",
      "Stationery",
      "Movies",
      "Mobile-Apps",
      "Fast Food",
      "Coffee",
      "Toys",
      "Magazines",
    ],
  },
  {
    min: 100,
    max: 300,
    category: [
      "lunch",
      "small-accessories",
      "stationary",
      "Groceries",
      "Dining-Out",
      "Entertainment",
      "Clothing",
      "Health",
      "Medicine",
      "Transportation",
      "Electronics",
      "Gifts",
    ],
  },
  {
    min: 300,
    max: 500,
    category: [
      "Movie-Tickets",
      "Books",
      "Pet-Supplies",
      "Outdoor-Activities",
      "Healthcare",
      "Concert-Tickets",
      "Travel-Accessories",
      "Art-Supplies",
      "Stationery",
      "Craft-Materials",
      "Fuel",
    ],
  },
  {
    min: 500,
    max: 1000,
    category: [
      "Electronics",
      "Home-Decor",
      "Fuel",
      "Kitchen-Appliances",
      "Fitness-Equipment",
      "Furniture",
      "Clothing",
      "Gadgets",
      "Subscription-Services",
      "Hobbies",
      "Gifts",
      "Shopping",
    ],
  },
  {
    min: 1000,
    max: 3000,
    category: [
      "Vacation",
      "Gadgets",
      "Fuel",
      "Home-Appliances",
      "Furniture",
      "Jewelry",
      "Electronics",
      "Fitness-Equipment",
      "Luxury-Items",
      "Hobbies",
      "Experiences",
      "Bank-Expenses",
    ],
  },
  {
    min: 3000,
    max: 6000,
    category: [
      "Electronics",
      "Home-Decor",
      "Fashion",
      "Travel",
      "Gym",
      "Maintainance",
      "Shopping",
      "Vacation",
      "Entertainment",
      "Bank-Expenses",
    ],
  },
  {
    min: 6000,
    category: [
      "Electronic-Gadgets",
      "Vacation",
      "Rent",
      "Shopping",
      "Investments",
      "Bank-Expenses",
    ],
  },
];
